### PR TITLE
Updating NAN to the latest version. This allows node 6.2.0 to be used.

### PR DESCRIPTION
**Pull request by michael-lawrence**
Fixes issue #106

### CODE REVIEW

**Comment by okofish** [comment]
+1 on this, I was having the same problem as Michael and this fixed it.

**Comment by drewish** [comment]
Looks good. Do you mind adding node 6 to the list of tested versions in the .travis.yml file?

**Comment by rileyjshaw** [comment]
Can we merge this?

**Comment by drewish** [comment]
Thanks for the ping, I didn't realize it's been updated.

**Comment by rileyjshaw** [comment]
Awesome—thanks @drewish and @michael-lawrence!

FYI, it doesn't look like this version has been published to npm yet :)

**Comment by rileyjshaw** [comment]
ping @drewish?

**Pull request merged**
