### PR TITLE
Update nan for io.js 2.x.x compatibility

### PR DESCRIPTION
**Pull request by imyller**
Referencing iojs/io.js#1620

### CODE REVIEW

**Comment by drewish** [comment]
Can we add that as a target for Travis to test on?

**Comment by justinlatimer** [comment]
@drewish Travis did use 2.0.0 - https://travis-ci.org/justinlatimer/node-midi/jobs/61371352
(the "iojs" target uses "a recent version of iojs")

**Comment by justinlatimer** [comment]
:+1:

**Comment by drewish** [comment]
Awesome, that what happens when you try to do PR review from the mobile web views

**Pull request merged**
