### PR TITLE
fix for closing virtual ports in osx

### PR DESCRIPTION
**Pull request by szymonkaliski**
Fixes https://github.com/justinlatimer/node-midi/issues/75

### CODE REVIEW

**Comment by justinlatimer** [comment]
Will have a look thanks! Did you submit the patch to RtMidi upstream - it's hosted on [GitHub](https://github.com/thestk/rtmidi) as well.

**Comment by szymonkaliski** [comment]
nope, but good thinking, I'll do that tomorrow! :)

**Comment by szymonkaliski** [comment]
Submitted there as well: https://github.com/thestk/rtmidi/pull/55

**Comment by szymonkaliski** [comment]
There's problem with virtual input as well, here's new PR: https://github.com/justinlatimer/node-midi/pull/96

**Comment by drewish** [comment]
Cool thanks for taking this upstream. Once it's merged we can pull it in and update our copy of rtmidi.

**Pull request closed without merging**
