### PR TITLE
upgrade to nan v2.0

### PR DESCRIPTION
**Pull request by julianduque**
Upgrade to NAN v2.0 API

### CODE REVIEW

**Comment by julianduque** [comment]
Not sure why io.js v3.0.0 failed on travis, I was able to build it properly on my local install

**Comment by drewish** [comment]
Looking at nan's example code I don't see any v8 includes. I wonder if we can just remove:
```
 #include <v8.h>
 #include <node.h>
 #include <node_object_wrap.h>
 #include <node_version.h>
```
And let NaN handle it? Curious if that would do anything about those errors.

**Comment by julianduque** [comment]
@drewish still the same errors, weird I can't reproduce those locally

**Comment by drewish** [comment]
Yeah looks like master is broken too. I'm going to play around with travis and see if I can get it building. If I can't figure something out pretty quickly I'll stop screwing around with it and just finish reviewing this. It seems like the broken build is independent of this.

**Comment by drewish** [comment]
Okay yeah this all seems legit. I'll screw with Travis without bothering you ;)

Thanks for the contribution!

**Pull request merged**
