### PR TITLE
Fix errors and deprecations for node 12.

### LINKED ISSUE #136: Install failed on node 12
It's a new V8 engine and too many errors are coming up for this now. Is this repo now abandonware? I've noticed there's not been any updates for quite a while

### PR DESCRIPTION
**Pull request by justinlatimer**
This should fix #136

### CODE REVIEW

**Comment by marksyzm** [comment]
Thank you so much, Justin!

**Comment by stevenleeg** [comment]
Amazing!! Thanks for fixing this, I'll test out later and report back if I see any issues.

**Comment by cleverplatypus** [comment]
Thanks @justinlatimer,
That was quick!

Can you bump version number and push to npm please?
Cheers

**Comment by justinlatimer** [comment]
Some other fixes I need to get in first! Will be soon though.

**Comment by justinlatimer** [comment]
v1.0.0 containing this fix published to npm.

**Pull request merged**
